[2024-08-07T06:26:48.515+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T06:26:48.556+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Integrate_Time_Location_Dimension.bronze_time manual__2024-08-07T06:26:33.885975+00:00 [queued]>
[2024-08-07T06:26:48.575+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Integrate_Time_Location_Dimension.bronze_time manual__2024-08-07T06:26:33.885975+00:00 [queued]>
[2024-08-07T06:26:48.576+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-07T06:26:48.612+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): bronze_time> on 2024-08-07 06:26:33.885975+00:00
[2024-08-07T06:26:48.617+0000] {standard_task_runner.py:63} INFO - Started process 4118 to run task
[2024-08-07T06:26:48.621+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Integrate_Time_Location_Dimension', 'bronze_time', 'manual__2024-08-07T06:26:33.885975+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/etl_time_location_dag.py', '--cfg-path', '/tmp/tmpo79suiej']
[2024-08-07T06:26:48.624+0000] {standard_task_runner.py:91} INFO - Job 170: Subtask bronze_time
[2024-08-07T06:26:48.721+0000] {task_command.py:426} INFO - Running <TaskInstance: Integrate_Time_Location_Dimension.bronze_time manual__2024-08-07T06:26:33.885975+00:00 [running]> on host 45f7764b2bf2
[2024-08-07T06:26:48.864+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Integrate_Time_Location_Dimension' AIRFLOW_CTX_TASK_ID='bronze_time' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T06:26:33.885975+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-07T06:26:33.885975+00:00'
[2024-08-07T06:26:48.865+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T06:27:00.662+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T06:27:00.663+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/timelocation/load_date.py", line 15, in readTimeExcel
    time_df = ps.read_excel('./data/SampleDateDim.xls', sheet_name='LoadDates', squeeze=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/pandas/namespace.py", line 1184, in read_excel
    pdf_or_psers = pd_read_excel(io_or_bin, sn=sheet_name, sq=squeeze)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/pandas/namespace.py", line 1147, in pd_read_excel
    return pd.read_excel(
           ^^^^^^^^^^^^^^
TypeError: read_excel() got an unexpected keyword argument 'squeeze'
[2024-08-07T06:27:00.680+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Integrate_Time_Location_Dimension, task_id=bronze_time, run_id=manual__2024-08-07T06:26:33.885975+00:00, execution_date=20240807T062633, start_date=20240807T062648, end_date=20240807T062700
[2024-08-07T06:27:00.895+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 170 for task bronze_time (read_excel() got an unexpected keyword argument 'squeeze'; 4118)
[2024-08-07T06:27:00.919+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-07T06:27:00.958+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-07T06:27:00.991+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
