[2024-08-07T05:42:00.817+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T05:42:00.852+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Integrate_Time_Location_Dimension.bronze_time manual__2024-08-07T05:41:47.746742+00:00 [queued]>
[2024-08-07T05:42:00.867+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Integrate_Time_Location_Dimension.bronze_time manual__2024-08-07T05:41:47.746742+00:00 [queued]>
[2024-08-07T05:42:00.867+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-07T05:42:00.903+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): bronze_time> on 2024-08-07 05:41:47.746742+00:00
[2024-08-07T05:42:00.908+0000] {standard_task_runner.py:63} INFO - Started process 1152 to run task
[2024-08-07T05:42:00.913+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Integrate_Time_Location_Dimension', 'bronze_time', 'manual__2024-08-07T05:41:47.746742+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/etl_time_location_dag.py', '--cfg-path', '/tmp/tmppwhkvvao']
[2024-08-07T05:42:00.916+0000] {standard_task_runner.py:91} INFO - Job 144: Subtask bronze_time
[2024-08-07T05:42:01.013+0000] {task_command.py:426} INFO - Running <TaskInstance: Integrate_Time_Location_Dimension.bronze_time manual__2024-08-07T05:41:47.746742+00:00 [running]> on host 45f7764b2bf2
[2024-08-07T05:42:01.165+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Integrate_Time_Location_Dimension' AIRFLOW_CTX_TASK_ID='bronze_time' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T05:41:47.746742+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-07T05:41:47.746742+00:00'
[2024-08-07T05:42:01.166+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T05:42:33.570+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T05:42:33.571+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/timelocation/load_date.py", line 15, in readTimeExcel
    .load(file)
     ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/sql/readwriter.py", line 307, in load
    return self._df(self._jreader.load(path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.IllegalArgumentException: Parameter "header" is missing in options.
[2024-08-07T05:42:33.598+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Integrate_Time_Location_Dimension, task_id=bronze_time, run_id=manual__2024-08-07T05:41:47.746742+00:00, execution_date=20240807T054147, start_date=20240807T054200, end_date=20240807T054233
[2024-08-07T05:42:33.634+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 144 for task bronze_time (Parameter "header" is missing in options.; 1152)
[2024-08-07T05:42:33.661+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-07T05:42:33.704+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-07T05:42:33.742+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
